using System;
using System.Collections.Generic; //generated by hovering over error on list and clicking on
                                  //"potential fixes", selected top namespace suggestion

namespace Collection_Tutorial
{
    class Program
    {
        static void Main(string[] args)
            
        {
            var rnd = new Random(); //class called random in c#
            var BowlingScores = new List<int>();

            for (var idx = 0; idx < 10; idx++) 
            {
                var BowlingScore = rnd.Next(0, 31); //second number needs to be one higher than the highest possible number
                BowlingScores.Add(BowlingScore);
                
            }

            var game = 0;
            foreach (var score in BowlingScores)
            {
                game +=score;
            }

            Console.WriteLine($"Bowling Score is {game}");
            
            
            ////create generic list
            //var listOfNumbers = new List<int>(); //generic connection will almost always look like this
            //listOfNumbers.Add(98);
            //listOfNumbers.Add(7);
            //listOfNumbers.Add(56);
            //listOfNumbers.Add(13);
            //listOfNumbers.Add(72);
            //listOfNumbers.Add(42);
            //listOfNumbers.Add(44);

            //var sum = 0;
            //foreach(var nbr in listOfNumbers) //goes through list and does something for each one,
            //                                  //when doing foreach do not manipulate the list inside the loop
            //{
            //    sum += nbr; // sum = sum + nbr; <<shortcut for this type of statement
            //}
            //Console.WriteLine($"Sum is {sum}");

            ////listOfNumbers.Count; <<property so don't need ()

        }
    }
}
